# -*- coding: utf-8 -*-
"""train_indian_recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WPKbMBDXLL4YuP9h-FsjBkyqCXbgpYkQ
"""

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pickle

# Load the dataset
df = pd.read_csv("indian_movies.csv")

# Combine title and genres
df['combined'] = df['title'] + ' ' + df['genres']

# Vectorize
cv = CountVectorizer(stop_words='english')
vector_matrix = cv.fit_transform(df['combined'])

# Compute similarity
similarity = cosine_similarity(vector_matrix)

# Save the model and data
pickle.dump(df, open('indian_movies.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))

print("✅ Model trained and files saved.")